name: Build and Push Image
run-name: Build and Push Image

on: [push]

permissions:
  contents: read
  packages: write

jobs:
 build-push-image:
   runs-on: ubuntu-latest
   steps:
     - name: Check out repository code
       uses: actions/checkout@v4

     - name: Build image
       run: docker build -t imageku .

     - name: List image
       run: docker images

     - name: Cek isi image
       run: docker history imageku:latest

     - name: Login to GitHub Container Registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         Username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Tag image
       run: docker tag imageku ghcr.io/zenna24/imageku:latest
                                                                                                                                            - name: Push image
       run: docker push ghcr.io/zenna24/imageku:latest
